language: node_js
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
node_js:
  - "lts/*"
  - "node"
after_success:
  - nyc npm test --reporter=text-lcov
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT